name: JBZD Scraper Test (20 jobs × 1000 users)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
      max-parallel: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install aiohttp

      - name: Run test scraper
        run: |
          python scripts/test_scrape_users.py \
            --test-count 20000 \
            --total-jobs 20 \
            --job-index ${{ matrix.job_index }} \
            --concurrency 5 \
            --outdir results/users_test
