name: Fetch JBZD Users

on:
  workflow_dispatch:

jobs:
  fetch_users:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_index: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Fetch users and save JSON
        run: python mikroblogusers/scripts/fetch_jbzd_users.py ${{ matrix.job_index }}

  commit_results:
    runs-on: ubuntu-latest
    needs: fetch_users
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Commit JSON files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add jobs_output/*.json
          git commit -m "Add JBZD user data JSON files [skip ci]" || echo "No changes to commit"
          git push
