name: Scrape JBZD Users

on:
  workflow_dispatch:

jobs:
  scrape:
    strategy:
      matrix:
        job_index: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests tqdm

      - name: Create results folder
        run: mkdir -p results

      - name: Run scraper
        run: |
          python scripts/scrape_users.py \
            --job-index ${{ matrix.job_index }} \
            --total-jobs 20 \
            --concurrency 5 \
            --output results/users_${{ matrix.job_index }}.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: users-${{ matrix.job_index }}
          path: results/users_${{ matrix.job_index }}.json

  merge_and_commit:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: results/

      - name: Move all JSONs to results root
        run: |
          find results -type f -name "*.json" -exec mv {} results/ \;

      - name: Commit merged files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add results/*.json
          git commit -m "Add all 20 users JSON files" || echo "No changes to commit"
          git push
