name: Fetch JBZD Users

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch_users:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_index: [0,1,2,3,4,5,6,7,8,9,
                    10,11,12,13,14,15,16,17,18,19,
                    20,21,22,23,24,25,26,27,28,29,
                    30,31,32,33,34,35,36,37,38,39,
                    40,41,42,43,44,45,46,47,48,49,
                    50,51,52,53,54,55,56,57,58,59,
                    60,61,62,63,64,65,66,67,68,69,
                    70,71,72,73,74,75,76,77,78,79,
                    80,81,82,83,84,85,86,87,88,89,
                    90,91,92,93,94,95,96,97,98,99]
    concurrency:
      group: jbzd-fetch
      cancel-in-progress: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Create output folder
        run: mkdir -p jobs_output

      - name: Run fetch script
        run: |
          echo "Running job index ${{ matrix.job_index }}"
          python scripts/fetch_jbzd_users.py ${{ matrix.job_index }} || (echo "Python script failed" && exit 1)

      - name: Upload artifact if exists
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: jbzd-job-${{ "%03d" | format(matrix.job_index) }}
          path: jobs_output/job_${{ matrix.job_index }}.json

  merge_and_commit:
    runs-on: ubuntu-latest
    needs: fetch_users
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: all_jobs

      - name: Merge into 20 final JSONs
        run: |
          python - <<'EOF'
          import json, os, math, glob

          files = sorted(glob.glob("all_jobs/*.json"))
          all_data = []
          for f in files:
              with open(f, encoding="utf-8") as fp:
                  data = json.load(fp)
                  all_data.extend(data)

          os.makedirs("jobs_output_final", exist_ok=True)
          chunk_size = math.ceil(len(all_data)/20)
          for i in range(20):
              chunk = all_data[i*chunk_size:(i+1)*chunk_size]
              with open(f"jobs_output_final/final_{i+1}.json", "w", encoding="utf-8") as fp:
                  json.dump(chunk, fp, ensure_ascii=False, indent=2)
          EOF

      - name: Commit final JSONs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add jobs_output_final/*.json
          git commit -m "Add final JBZD user JSON files [skip ci]" || echo "No changes to commit"
          git push
