name: Scrape JBZD Users

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_index: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests tqdm

      - name: Run scraper
        run: |
          python scripts/scrape_users.py \
            --job-index ${{ matrix.job_index }} \
            --total-jobs 20 \
            --concurrency 50 \
            --output results/users_${{ matrix.job_index }}.json
